### ISSUE TITLE
Passing Parameters with single quote (')

### ISSUE THREAD

**Issue by mamdouht** [HedgehogDevelopment/UpdatePackageInstaller#4]
Passing the parameters like below will create an issue (directory doesnt exist,...)
PackageInstaller.exe -p 'C:\path\TDS_Items.update' -u 'http://sitecore9local' -f 'C:\inetpub\wwwroot\Sitecore9Local' -v 'true'

it has to be like:
PackageInstaller.exe -p C:\path\TDS_Items.update -u http://sitecore9local -f C:\inetpub\wwwroot\Sitecore9Local -v 'true'

restitution to this may be to trim (') for the args/

**Comment by cturano** [comment]
I don't think this is a bug. Entering the following into a command window gives a similar error:

dir 'c:\'

Double quotes are meant to be used to surround parameters with spaces in them. Single quotes are considered part of the parameter.

**Comment by mamdouht** [comment]
Sorry i meant to post this on another repo 
https://github.com/JackTheHack/Sitecore.TDS.AdvancedPackageInstaller/tree/9.0.171002

the usage example there is:
Tools\PackageInstaller.exe -p 'TDS.PackageName.update' -u 'http://localhost' -f 'C:\inetpub\Sitecore\Website' -v 'true'

which doesnt work. 

i agree with your point quotes or double quotes are used for names with spaces.  

that will make it easier on users, if there is empty space in the argument ignore otherwise trim.
anyhow, it just my experience and its up to you guys.
